edition = "2021"
imports_granularity = "Crate"
max_width = 140
match_block_trailing_comma = true
newline_style = "Unix"
normalize_comments = true
tab_spaces = 2
where_single_line = true
use_field_init_shorthand = true
use_try_shorthand = true

