-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."companies" add column "is_wagon_owner" boolean
--  not null default 'false';
