/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppLayout: typeof import('./../components/AppLayout/AppLayout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./../components/Sidebar/Sidebar.vue')['default']
    SidebarMenuItem: typeof import('./../components/Sidebar/SidebarMenuItem.vue')['default']
    Titlebar: typeof import('./../components/Titlebar/Titlebar.vue')['default']
    Topbar: typeof import('./../components/Topbar/Topbar.vue')['default']
  }
}
